### ISSUE TITLE
Service layer에서 사용하는 request promise의 에러 핸들링이 불가능한 이슈

### ISSUE THREAD

**Issue by voidsatisfaction** [parksb/the-camp-lib#15]
```js
  const response = await requestPromise(options, (err, res, body) =>; {    if (err) {      throw new Error(err);    }
    addLog('fetchSoldier', `${res.statusCode} ${res.statusMessage}`);
    if (res.statusCode === 200 &amp;&amp; body.resultCd !== '9999') {      throw new Error(body.resultMsg || '알 수 없는 에러.');    }  });
```

fetchSoldier 서비스의 코드 예시인데요, 현재 requestPromise를 사용중인데, callback으로 에러 처리를 하고 있어서, 이 서비스에 의존하는 다른 모듈에서 error 캐치가 불가능한 상황입니다.. ㅠㅠ

callback내부의 에러 처리 로직을 바깥으로 빼야할것 같은데, 어떻게 생각하세요?

**Comment by parksb** [comment]
이슈레이징 감사합니다 :) #16 에서 해결되었고, [v2.4.0](https://github.com/parksb/the-camp-lib/releases/tag/v2.4.0)에 적용되었습니다.
